mydata <- read.table("household_power_consumption.txt", header=TRUE, sep=';', na.strings="?", nrows=71000, stringsAsFactors=FALSE)
str(mydata)
mydata <- within(mydata, DateTime <- as.POSIXlt(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S"))
mydata <- subset(mydata, DateTime >= as.POSIXlt("2007-02-01") & DateTime < as.POSIXlt("2007-02-03"))
par(mfrow=c(2,2))
plot(mydata$DateTime, mydata$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(mydata$DateTime, mydata$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(mydata$DateTime, mydata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(mydata$DateTime, mydata$Sub_metering_2, col="red")
lines(mydata$DateTime, mydata$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1, bty="n")
plot(mydata$DateTime, mydata$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, "plot4.png")
dev.off()